name: Test (macOS)

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-13
    steps:
    - name: List Xcodes
      run: ls /Applications
    - name: Force Xcode 15.0
      run: sudo xcode-select -switch /Applications/Xcode_15.0.app
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: cd "Example" && swift test
